print("Hello World")
print(1)
print(1, 2, 3)
print(1 + 1)
print(10 - 2.2)
print(3 * 8)
print(3 + (4 * 6) + 7 - 8)
print('*' * 80)
print("Ahoj" + " " + "PyChaps")
print("Soucet cisel 3 a 8 je", 3 + 8)
print('Mama ma misu')
print('V mise je maso')
print('Jedna a pul je', 1 + 0.5)